### PR TITLE
Closes zurb/foundation-sites#10177 - Build edits!

### PR DESCRIPTION
**Pull request by IamManchanda**
Closes zurb/foundation-sites#10177
PS: I am using CLI so let me know if this was a mistake for manual :smile:

### CODE REVIEW

**Comment by IamManchanda** [comment]
Wait .... can `foundation watch` be used in manual setup ??
If not let me know ... i will update my PR with edits :smile: 
Poke @kball

**Comment by marvinhuebner** [comment]
`foundation watch` can't be used in a manual setup if the user has not installed the foundation cli globally. You need to type in the terminal `npm start`.

The `foundation watch` command in the cli does the same (see: https://github.com/zurb/foundation-cli/blob/master/lib/commands/watch.js#L13).

Here you can see which commands belong to the cli in a manual setup:

- `npm start` = `foundation watch`
- `npm run build` = `foundation build`

**Comment by IamManchanda** [comment]
@marvinhuebner sorry saw your comment late... i mean just now!

I am updating my PR ... thanks!

**Comment by IamManchanda** [comment]
Done @marvinhuebner @kball... can we get this review/merge ??

**Comment by marvinhuebner** [comment]
Basically this look good for me.

I reconsider if it is necessary to write down the normal npm commands in the section "Using the CLI". If someone uses the CLI the `foundation` command is definitely available. Maybe this confuses a little bit. But one the other side this would clarify whats under the hood.

**Comment by IamManchanda** [comment]
`or` is mentioned properly

**Comment by kball** [comment]
I'm a little confused about why we need both in the section that is explicitly describing using the Foundation CLI... perhaps instead of posing them at equal importance we can explain what `foundation watch` is doing and mention that if you installed in another way `npm start` should work the same?

**Review by ncoden — APPROVED** [review]
I resolved the conflicts with `master`. LGTM.

**Pull request merged**
