### PR TITLE
chore: bump gulp-sass to 3.1.0 for Node 8+ compatibility

### PR DESCRIPTION
**Pull request by colin-marshall**
Related Issue: https://github.com/zurb/foundation-sites/issues/10863

### CODE REVIEW

**Review by ncoden — COMMENTED** [review]
I don't find a minimum node version for `gulp-sass`. Do you have any info about that ?

According to our `README.md` it should be compatible with node `0.12 or greater`

**Comment by colin-marshall** [comment]
I'm not sure about `gulp-sass`, but version `3.1.0` uses `node-sass` `4.2.0`, which is compatible with node 0.10+ according to the release page:
https://github.com/sass/node-sass/releases/v4.2.0

**Comment by colin-marshall** [comment]
There's also this `gulp-sass` issue suggesting they require Node v4, so I would take that to mean it currently requires less than that.
https://github.com/dlmanning/gulp-sass/issues/648

That issue brings up that currently, only versions of Node >= 4 are maintained. According to the [Node maintenance calendar](https://github.com/nodejs/Release) Node v4 will no longer be maintained after April 30th of this year. Maybe it's time we bump up the requirements from v0.12 for our templates. Building the docs in the `foundation-sites` repo does require Node v4 after all. That's unrelated to the templates, but still...

**Comment by DanielRuf** [comment]
Generally the gulp ecosystem with all the gulp plugins is not great. We should directly use node-sass. Afaik it is planned to completely migrate to webpack.

**Comment by DanielRuf** [comment]
See https://github.com/zurb/foundation-sites/issues/10863#issuecomment-358753129

We also have projects at work that use Node.js 8 with the default Foundation Sites template and `node-sass` always worked after it was built by `node-gyp`. If there are no binaries it is ok. `node-sass` has to and should be compiled with `node-gyp`. There are not releases for all OS and OS versions.

**Comment by colin-marshall** [comment]
@DanielRuf is this worth merging prior to us moving to node-sass with webpack?

**Comment by DanielRuf** [comment]
It should be fine to merge. node-sass can be built for any Node.js version from 0.12 up.

**Review by ncoden — APPROVED** [review]

**Pull request merged**
