### PR TITLE
fix: use terser as uglify throws a super expression error

### LINKED ISSUE #11882: Uncaught TypeError: Super expression must either be null or a function with BUILD
I'm getting this error when using the foundation-explicit-pieces.js and customize it to my needs.
But ONLY when i use foundation build. With foundation watch everything works just fine.

It doesnt matter which lib i turn off or on, tested with everything off and only left
`import { Foundation } from 'foundation-sites/js/foundation.core';` this works fine, but when i turn on 
`import { OffCanvas } from 'foundation-sites/js/foundation.offcanvas';` it gives me the error when using build.

## What should happen?
It should build without any errors
...

## What happens instead?
Receiving this error: **Uncaught TypeError: Super expression must either be null or a function**
...

## Possible Solution
...

## Test Case and/or Steps to Reproduce (for bugs)
How to reproduce:
1. Foundation new
2. Select Zurb template
3. Open app.js
4. Uncomment `import './lib/foundation-explicit-pieces';`
5. Comment out `require('foundation-sites');`
6. Open foundation-explicit-pieces.js and comment out some imports
7. Run command **foundation build**

## Context
This error stops running any of the javascript following `$(document).foundation();`
...

## Your Environment
- Foundation version(s) used: Foundation CLI 2.2.5 & foundation-sites: ^6.5.1
- Browser(s) name and version(s): Google Chrome Version 77.0.3865.120 (Official Build) (64-bit)
- Device, Operating System and version: iMac macOS High Sierra version 10.13.6
- Node version: v10.15.0
- NPM version: 6.10.3

## Checklist
- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

### PR DESCRIPTION
**Pull request by DanielRuf**
This PR should resolve https://github.com/foundation/foundation-sites/issues/11882

### CODE REVIEW

**Comment by kevinmu17** [comment]
Whats the normal merge speed at foundation for these PR's??

**Comment by DanielRuf** [comment]
> Whats the normal merge speed at foundation for these PR's??

When we have time =)
And when someone does a review and has the rights to merge. I do not have the needed rights in this repository.

Why do you ask?

**Comment by DanielRuf** [comment]
If you need it now you can use https://patch-diff.githubusercontent.com/raw/foundation/foundation-zurb-template/pull/97.patch or https://patch-diff.githubusercontent.com/raw/foundation/foundation-zurb-template/pull/97.diff and use patch-package / patch / git apply and build Foundation from source or use the source files.

**Comment by kevinmu17** [comment]
I am just curious because there are multiple PR's which are relatively small to merge and are open for quite some time now. In my opinion this one is pretty crucial for an optimised build of foundation :) I need to throw a site in production next week so...

But hey, your patch suggestion works like a charm! Patching with git is a new one for me, just applied and tested it (it works yiha!)

I made a little addition to the gulpfile.babel.js:
`.pipe($.if(PRODUCTION, $.terser({ output: {comments: false} })
      .on('error', e => { console.log(e); })
    ))
`

This removes any commenting/documentation in the build output (just like uglify did), What do you think?

**Comment by DanielRuf** [comment]
> I made a little addition to the gulpfile.babel.js:
> `.pipe($.if(PRODUCTION, $.terser({ output: {comments: false} }) .on('error', e => { console.log(e); }) )) `
> 
> This removes any commenting/documentation in the build output (just like uglify did), What do you think?

Thanks for the input. I will add it this week, probably this evening.

**Comment by DanielRuf** [comment]
Generally I can not reproduce the issue regarding the comments when I test with terser.

Can you provide a small reproducible testcase?

**Comment by DanielRuf** [comment]
Because `comments` is set to `false` by default. See https://github.com/terser/terser/blob/master/README.md#output-options

Also this may depend on the case if you are in dev or prod environment.

**Comment by kevinmu17** [comment]
Ah okay, In all my tested cases it's showing comments so there must be something from at my end. I'll investigate this and let you know if I can find the possible "problem"

**Comment by lundmorten** [comment]
> But hey, your patch suggestion works like a charm! Patching with git is a new one for me, just applied and tested it (it works yiha!)

@kevinmu17 – Patching with git is also new for me. Can you please explain the steps on how to do it? :)

**Comment by kevinmu17** [comment]
cd to your project folder and do this:
`curl https://patch-diff.githubusercontent.com/raw/foundation/foundation-zurb-template/pull/97.patch | git apply -`

Note: this only works if you didn't change anything in your package.json or package-lock.json. It will throw you an error.

**Comment by lundmorten** [comment]
@kevinmu17  Great, thanks! :+1: 
I tried it successfully on a new project, with no changes to package.json. But all my previous projects have changes, so it does not work.

**Comment by DanielRuf** [comment]
> I tried it successfully on a new project, with no changes to package.json. But all my previous projects have changes, so it does not work.

You can use [`patch-package`](https://npmjs.com/patch-package) for that.

**Comment by DanielRuf** [comment]
> I tried it successfully on a new project, with no changes to package.json. But all my previous projects have changes, so it does not work.

You can probably use [`patch-package`](https://npmjs.com/patch-package) for that.

**Comment by joeworkman** [comment]
This pull request has been mentioned on **Foundation Open Source Community**. There might be relevant details there:

https://foundation.discourse.group/t/gulpfile-compiling-app-js-incorrectly-with-bloated-code/1656/14

**Pull request merged**
