### PR TITLE
[Enhancement] live css reinjection

### PR DESCRIPTION
**Pull request by ppowalowski**
Allows browserSync to reinject CSS without page reload on style changes.

### CODE REVIEW

**Comment by gakimball** [comment]
Why does `browser.reload` not need to trigger when HTML files change?

**Comment by ppowalowski** [comment]
It is triggered, but by a separate watch looking for changes inside `dist`. on [Line 176](https://github.com/zurb/foundation-zurb-template/pull/23/files#diff-b9e12334e9eafd8341a6107dd98510c9R176)

**Reason:** after long time of trying and frustration I noticed `['pages', browser.reload]` caused unwanted full reloads (node 5.1.0). This prevented marvelous css injection from working properly.
I am little puzzled about the exact source of the problem because supposedly the (task)notation inside of an array caused this misbehavior. I moved it to a separate task passing `browser.reload` directly. It works treated as cb parameter: see [Gulp Doc](https://github.com/gulpjs/gulp/blob/master/docs/API.md#cbevent) and [gulp.watch](https://github.com/gulpjs/gulp/blob/master/index.js#L27) 
Not sure if the overall notation is state of the art like this. At least it works ;-)

Watching `dist` instead of source due to serving of `dist` fits semantically nevertheless. When watching final result page, proper reloads are triggered even if external changes take place.

What do you think?

**[edit]**: maybe wrapping `browser.reload` inside a `gulp.task` could help at this point.

**Comment by ppowalowski** [comment]
Hi,
have been out for christmas holidays ;-)

now i recognized how big of a mess `gulp.watch` is:
[gulp.watch definition](https://github.com/gulpjs/gulp/blob/master/index.js#L27):
`cb` only works if `opts` actually is `cb` or if it is an object ([gaze](https://github.com/shama/gaze) options object) as seen here:
[gulp.watch / glop-watcher is a wrapper for gaze](https://github.com/gulpjs/glob-watcher/blob/v0.0.8/index.js#L12)

Obviously documentation doesn't cover this unhandy behavior. Also I am confused why they didn't use gaze directly.

`browser.reload` only works properly if called as callback and not when applied and bound as [gulp task](https://github.com/gulpjs/gulp/blob/master/index.js#L36). We need to find a way to ship around this issue. Duplicating all watchers to allow documented `cb` functionality would be ugly.

Share your thoughts.

**[edit]**:

Okay, I fed the devil ;-)

Wrapping `browser.reload` with a task as [mentioned](https://github.com/zurb/foundation-zurb-template/pull/23#issuecomment-163392094) works like a charm allowing browserSync to properly digest the stream inside `sass` task without breaking.

Check out  a99499d.

This should do the job until a better gulp comes along.

**Comment by ppowalowski** [comment]
Okay, I fed the devil ;-)

Wrapping `browser.reload` with a task as [mentioned](https://github.com/zurb/foundation-zurb-template/pull/23#issuecomment-163392094) works like a charm allowing browserSync to properly digest the stream inside `sass` task without breaking.

Check out  a99499d.

This should do the job until a better gulp comes along.

**Comment by gakimball** [comment]
Opened PR #28 which updates the template to Gulp 4. The creators of Gulp say v4 is production-ready, even though it's not "done" yet. From what I can tell it works totally fine. Take a look when you have time!

**Pull request merged**
